export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REFRESH_TOKENS = 'AUTH_REFRESH_TOKENS';
export const AUTH_AUTO_REFRESH_TOKENS = 'AUTH_AUTO_REFRESH_TOKENS';
export const AUTH_REFRESH_TOKEN_TASK = 'AUTH_REFRESH_TOKEN_TASK';
